services:
  - type: web
    name: deepfake-detector
    runtime: python
    python:
      version: "3.10"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: "gunicorn --workers 1 --threads 1 --timeout 180 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PORT
        value: "10000"
    plan: free
    disk:
      name: model_storage
      mountPath: /opt/render/project/src/models/
      sizeGB: 2